[theme]
primaryColor = "#c80000"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f5f5"
textColor = "#000000"

[server]
headless = true

[ui]
favicon = "https://raw.githubusercontent.com/MKato2361/Report_maker/main/static/apple-touch-icon.png"
pageTitle = "故障報告書自動作成"

[client]
toolbarMode = "minimal"
